version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    env_file:
      - .env # Ensure this points to your .env file with the correct variables
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data:
